version: '2'
services:
  rtty:
    container_name: zl_rtty
    build:
      dockerfile: Dockerfile
      context: rttyc
    restart: always
    tty: true
    ports:
      - '23222:22'
    volumes:
      - ./supervisord-rtty.conf:/etc/supervisor/conf.d/supervisord-rtty.conf
    environment:
      - HOST=192.168.199.140
      - DEVICE=eth0
      - DESCRIPTION=fuck
  rttys:
    container_name: zl_rttys
    build:
      dockerfile: Dockerfile
      context: rttys
    restart: always
    tty: true
    ports:
      - '25912:5912'
    volumes:
      - ./supervisord-rttys.conf:/etc/supervisor/conf.d/supervisord-rttys.conf



